### PR TITLE
pass popstate event to oldhandler

### PR DESCRIPTION
**Pull request by rdwallis**
One character fix.  Passes the onpopstate event to any existing handlers.

The test case was failing because Gwt.Create(History.class) was being called twice.   Only one History handler would work before this patch, so creating two wasn't a problem until that was fixed.

### CODE REVIEW

**Comment by drmichaelgorski** [comment]
+1

**Comment by rdwallis** [comment]
@jbarop are you still maintaining gwt-pushstate?

**Comment by jbarop** [comment]
Yes. I'm currently in a non GWT project which is really time consuming because we're near go-live.

I think I can catch up on the coming public holidays in Germany.

**Comment by rdwallis** [comment]
ok no worries on the delay then.  Hope your launch goes well.

**Comment by rdwallis** [comment]
@jbarop please can you merge this and do a maven release.

**Comment by rdwallis** [comment]
@jbarop I want to include gwt-pushstate as a default feature in the [new gwtp-plugin](https://github.com/ArcBees/gwtp-eclipse-plugin/pull/86) but version 1.0.0 has some problems that are now fixed in 1.1.0-SNAPSHOT and this branch as well.  Please can you merge this and do a new sonatype release.  If you don't want to continue maintaining this project please can you make me a collaborator.

**Comment by drmichaelgorski** [comment]
@rdwallis I extended this project to make it work with GWTP Routeplacetokens as well. You can find it here: https://github.com/confile/gwt-pushstate

**Pull request merged**
