### PR TITLE
Upgrade to GWT 2.6.0

### PR DESCRIPTION
**Pull request by mwuertinger**
- Changes the GWT version to 2.6.0.
- Changes the library version to 2.6.0-SNAPSHOT in order to reflect the
  potential incompatibilities caused by this change.

### CODE REVIEW

**Comment by v-antech** [comment]
Would be great if this gets approved soon :+1:

**Comment by drmichaelgorski** [comment]
+1 I hope so too.

**Comment by jbarop** [comment]
I'll set the project.version back to 1.1

My plan:
1.0 - gwt-2.5
1.1 - gwt-2.6
1.2 - gwt-2.7

What do you think?

**Comment by mwuertinger** [comment]
I personally think it's easiest to manage if the versions are aligned with GWT but if you prefer a different version scheme I'm also OK with that.

**Comment by v-antech** [comment]
I have to agree with mwuertinger, keeping the versions in sync with GWT will be much easier to immediately see which version of the library is built with which corresponding GWT version.

**Pull request merged**
